CarLearning:
  measure: reward
  thresholds: [4.0, 4.0, 4.0]
  min_lesson_length: 80
  signal_smoothing: true
  parameters:
    movement_speed: [5.0, 5.0, 5.0, 5.0]
    pedestrian_speed_randomizer: [0.5, 0.75, 1.0, 1.0]
    spawn_rate_single: [12.5, 13.5, 15.0, 15.0]
    spawn_rate_curve: [12.5, 13.5, 15.0, 15.0]
    spawn_rate_crossing: [40.0, 45.0, 50.0, 50.0]
    pedestrian_rotation_randomizer: [0.5, 0.75, 1.0, 1.0]